In [1]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

## Load the training data into feature matrix, class labels, and event ids:

In [2]:
from proj1_helpers import *
DATA_TRAIN_PATH = 'data/train.csv'
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

In [3]:
from preprocessing import *
from linear_regression import *
from polynomial_regression import *
from gradient_descent import *
from stochastic_gradient_descent import *
from ridge_regression import *
from logistic_regression import *
from penalized_logistic_regression import *

## Do your thing crazy machine learning thing here :) ...

##### General preprocessing

In [4]:
ty,tXcl,ids=general_cleaning (y, tX, ids)

##### 1.Delete rows with NaNs in the first column

In [6]:
y1,tXcl1,ids1=first_column_nan_deleting(ty,tXcl,ids)

1.1. Drop correlated columns

In [8]:
tX_11=drop_correlated_columns_nan_deleted(tXcl1)

Standartization

In [10]:
tX_11=standartization(tX_11)

##### Build models

###### Linear regression

In [12]:
w_list,loss_list=LinearRegressionSubmission(y1,tX_11)
loss_list

[0.8655253268669649,
 0.9146404549646151,
 0.8531872782441865,
 0.9358064809053154]

###### Polynomial regression

In [135]:
deg,min=PolynomialRegressionSubmission(y1,tX_11,degrees=[i for i in range(12)],k_fold=4,seed=1)

Best degree for subset 0: 1, test error: 0.7919284693081986
Best degree for subset 1: 3, test error: 0.8421616433385937
Best degree for subset 2: 3, test error: 0.8036165091579167
Best degree for subset 3: 4, test error: 0.8198653741363071


###### Ridge regression

In [274]:
gammas,lambdas,losses=RidgeRegressionSubmission(y1,tX_11,num_degrees=5,k_fold=4,seed=1,lambdas=np.logspace(-2,1,15))

Best parameters for 0 subset are: 1 0.01  with error:  0.7929677144488401
Best parameters for 1 subset are: 3 0.01  with error:  0.842628569172011
Best parameters for 2 subset are: 4 0.07196856730011521  with error:  0.8013593228595915
Best parameters for 3 subset are: 4 0.01  with error:  0.8170814522760204


###### Gradient descent

In [168]:
w_list, loss_list=GradientDescentSubmission(y1,tX_11, max_iters=1000, gamma=0.5)
loss_list

[0.8655253268669649,
 0.9146404549646151,
 0.8531872782441867,
 0.9358064809053154]

###### Stochastic gradient descent

In [169]:
w_list, loss_list=StochasticGradientDescentSubmission(y1, tX_11,max_iters=1000,gamma=0.001,batch_size=1)
loss_list

[0.8971604482441596,
 0.9327958390494234,
 0.8776615026658197,
 0.9569188200422423]

###### Logistic regression

In [9]:
w_list, loss_list=LogisticRegressionSubmission(y1, tX_11, max_iter=10000,threshold=1e-6,gamma=0.00001)

Best loss for subset 0=-33252.11872884919
Best loss for subset 1=-39627.02335862964
Best loss for subset 2=-24978.562633395588
Best loss for subset 3=-11282.474679175222


###### Logistic penalized regression

In [35]:
res_gammas,res_lambdas,res_losses=PenalizedLogisticRegressionValidation(y1, tX_11, max_iters=2000,threshold=1e-6,k_fold = 4,seed=1,gammas = [0.00001,0.000001,0.0000001],lambdas =[0.0001,0.001,0.01,0.1,0.5])
res_losses

Best parameters for 0 subset are: 1e-05 0.001  with error:  -33290.784163721226
Best parameters for 1 subset are: 1e-05 0.5  with error:  -39649.15420012266
Best parameters for 2 subset are: 1e-05 0.5  with error:  -25005.05997738056
Best parameters for 3 subset are: 1e-05 0.001  with error:  -11312.821051492407


[-33290.784163721226,
 -39649.15420012266,
 -25005.05997738056,
 -11312.821051492407]

In [36]:
w_list, loss_list=PenalizedLogisticRegressionSubmission(y1, tX_11, max_iters = 2000,threshold = 1e-6,gammas = res_gammas,lambdas = res_lambdas)
loss_list

[array([[-33252.10504224]]),
 array([[-39625.09924197]]),
 array([[-24976.38451715]]),
 array([[-11283.1753931]])]

1.2. Don't drop correlated columns

In [11]:
tX_12=tXcl1[:]

Standartization

In [13]:
tX_12=standartization(tX_12)

##### Build models

###### Linear regression

In [14]:
w_list,loss_list=LinearRegressionSubmission(y1,tX_12)
loss_list

[0.8647537511511847,
 0.9144678771346525,
 0.8505369018167519,
 0.9338663179974429]

###### Polynomial regression

In [178]:
deg,min=PolynomialRegressionSubmission(y1,tX_12,degrees=[i for i in range(12)],k_fold=4,seed=1)

Best degree for subset 0: 1, test error: 0.7915800262354789
Best degree for subset 1: 3, test error: 0.8347865851048581
Best degree for subset 2: 4, test error: 0.7843550956691419
Best degree for subset 3: 4, test error: 0.7972454371526613


###### Ridge regression

In [179]:
gammas,lambdas,losses=RidgeRegressionSubmission(y1,tX_12,num_degrees=5,k_fold=4,seed=1,lambdas=np.logspace(-2,1,8))

Best parameters for 0 subset are: 1 0.01  with error:  0.7926336688403303
Best parameters for 1 subset are: 3 0.01  with error:  0.8370794764896661
Best parameters for 2 subset are: 4 0.01  with error:  0.785595954866555
Best parameters for 3 subset are: 4 0.01  with error:  0.7989338581963376


###### Gradient descent

In [237]:
w_list, loss_list=GradientDescentSubmission(y1,tX_12, max_iters=1000, gamma=0.05)
loss_list

[0.8649898904578096, 0.9148692677443079, 0.8507563885430097, 0.934309052790843]

###### Stochastic gradient descent

In [238]:
w_list, loss_list=StochasticGradientDescentSubmission(y1, tX_12,max_iters=1000,gamma=0.01,batch_size=1)
loss_list

[0.8978291300010686,
 0.9612131667381086,
 0.9560577372562178,
 1.0383759283176628]

###### Logistic regression

In [163]:
w_list, loss_list=LogisticRegressionSubmission(y1, tX_12, max_iter=10000,threshold=1e-6,gamma=0.00001)


Best loss for subset 0=-33233.5107167938


Best loss for subset 1=-39556.656572097665


Best loss for subset 2=-24672.61290494673


Best loss for subset 3=-11231.31214426626



###### Logistic penalized regression

In [15]:
res_gammas,res_lambdas,res_losses=PenalizedLogisticRegressionValidation(y1, tX_12, max_iters=2000,threshold=1e-6,k_fold = 4,seed=1,gammas = [0.00001,0.000001,0.0000001],lambdas =[0.0001,0.001,0.01,0.1,0.5])
res_losses

Best parameters for 0 subset are: 1e-05 0.0001  with error:  -33275.3821029691
Best parameters for 1 subset are: 1e-05 0.001  with error:  -39580.400210822634
Best parameters for 2 subset are: 1e-05 0.5  with error:  -24706.225266526264
Best parameters for 3 subset are: 1e-05 0.0001  with error:  -11266.27453003462


[-33275.3821029691,
 -39580.400210822634,
 -24706.225266526264,
 -11266.27453003462]

In [16]:
w_list, loss_list=PenalizedLogisticRegressionSubmission(y1, tX_12, max_iters = 2000,threshold = 1e-6,gammas = res_gammas,lambdas = res_lambdas)
loss_list

[array([[-33233.66688741]]),
 array([[-39556.65344101]]),
 array([[-24669.31854236]]),
 array([[-11231.64203219]])]

In [20]:
w=w_list[:]
acc=[]
#Accuracy
for i in range(4):
    print('Accuracy for subset {i} is {acc}'.format(i=i,acc=np.sum(np.where(sigmoid(np.c_[np.ones((y1[i].shape[0], 1)), tX_12[i]]@w[i])>0.5,1,0)==((y1[i].reshape(y1[i].shape[0],1)+1)/2.0).astype('int'))/y1[i].shape[0]))
    acc.append(np.sum(np.where(sigmoid(np.c_[np.ones((y1[i].shape[0], 1)), tX_12[i]]@w[i])>0.5,1,0)==((y1[i].reshape(y1[i].shape[0],1)+1)/2.0).astype('int'))/y1[i].shape[0])

Accuracy for subset 0 is 0.787708361566608
Accuracy for subset 1 is 0.694392843874139
Accuracy for subset 2 is 0.7359520947983216
Accuracy for subset 3 is 0.7196306859380287


##### 2.Replace rows with NaNs in the first column with mean values

In [37]:
tXcl2=first_column_nan_substitute(tXcl)
y2=ty[:]
ids2=ids[:]

2.1. Drop correlated columns

In [38]:
tX_21=drop_correlated_columns_nan_substituted(tXcl2)

Standartization

In [40]:
tX_21=standartization(tX_21)

##### Build models

###### Linear regression

In [41]:
w_list,loss_list=LinearRegressionSubmission(y2,tX_21)
loss_list

[0.8854946635070715,
 0.9095655755698142,
 0.8444161085281339,
 0.9356393670561948]

###### Polynomial regression

In [259]:
deg,min=PolynomialRegressionSubmission(y2,tX_21,degrees=[i for i in range(12)],k_fold=4,seed=1)

Best degree for subset 0: 1, test error: 0.7380293813836168
Best degree for subset 1: 3, test error: 0.8259035310516788
Best degree for subset 2: 3, test error: 0.8082072627789713
Best degree for subset 3: 3, test error: 0.8077675881019319


###### Ridge regression

In [260]:
gammas,lambdas,losses=RidgeRegressionSubmission(y2,tX_21,num_degrees=5,k_fold=4,seed=1,lambdas=np.logspace(-2,1,8))

Best parameters for 0 subset are: 1 0.01  with error:  0.7387782107877823
Best parameters for 1 subset are: 4 0.02682695795279726  with error:  0.8220307965200957
Best parameters for 2 subset are: 4 0.01  with error:  0.8085692503252808
Best parameters for 3 subset are: 3 0.01  with error:  0.8093161658986808


###### Gradient descent

In [261]:
w_list, loss_list=GradientDescentSubmission(y2,tX_21, max_iters=1000, gamma=0.5)
loss_list

[0.8854946635070715,
 0.9095655755698142,
 0.8444161085281339,
 0.9356393670561948]

###### Stochastic gradient descent

In [262]:
w_list, loss_list=StochasticGradientDescentSubmission(y2, tX_21,max_iters=1000,gamma=0.001,batch_size=1)
loss_list

[0.9144629822800107,
 0.9277818853983163,
 0.8741086265345123,
 0.9508634497055394]

###### Logistic regression

In [263]:
w_list, loss_list=LogisticRegressionSubmission(y2, tX_21, max_iter=10000,threshold=1e-6,gamma=0.00001)

Best loss for subset 0=-39102.27490455411
Best loss for subset 1=-41959.30321668912
Best loss for subset 2=-26173.11247717419
Best loss for subset 3=-11740.7069878609


###### Logistic penalized regression

In [42]:
res_gammas,res_lambdas,res_losses=PenalizedLogisticRegressionValidation(y2, tX_21, max_iters=2000,threshold=1e-6,k_fold = 4,seed=1,gammas = [0.00001,0.000001,0.0000001],lambdas =[0.0001,0.001,0.01,0.1,0.5])
res_losses

Best parameters for 0 subset are: 1e-05 0.0001  with error:  -39121.0577721062
Best parameters for 1 subset are: 1e-05 0.5  with error:  -41995.54136541851
Best parameters for 2 subset are: 1e-05 0.5  with error:  -26208.13543218638
Best parameters for 3 subset are: 1e-05 0.001  with error:  -11774.2246217849


[-39121.0577721062, -41995.54136541851, -26208.13543218638, -11774.2246217849]

In [ ]:
w_list, loss_list=PenalizedLogisticRegressionSubmission(y2, tX_21, max_iters = 2000,threshold = 1e-6,gammas = res_gammas,lambdas = res_lambdas)
loss_list

2.2. Don't drop correlated columns

In [46]:
tX_22=tXcl2[:]

Standartization

In [48]:
tX_22=standartization(tX_22)

##### Build models

###### Linear regression

In [49]:
w_list,loss_list=LinearRegressionSubmission(y2,tX_22)
loss_list

[0.8854930845038358,
 0.9092337659068742,
 0.8433782955671758,
 0.9343474433199054]

###### Polynomial regression

In [267]:
deg,min=PolynomialRegressionSubmission(y2,tX_22,degrees=[i for i in range(12)],k_fold=4,seed=1)

Best degree for subset 0: 1, test error: 0.7380763150136135
Best degree for subset 1: 5, test error: 0.814869875083629
Best degree for subset 2: 3, test error: 0.7863620919191471
Best degree for subset 3: 4, test error: 0.7896934963140386


###### Ridge regression

In [52]:
degrees,lambdas,losses=RidgeRegressionSubmission(y2,tX_22,num_degrees=8,k_fold=4,seed=1,lambdas=np.arange(0.0001,1,0.05))

Best parameters for 0 subset are: 1 0.0001  with error:  0.7380539413813467
Best parameters for 1 subset are: 5 0.050100000000000006  with error:  0.806331753108808
Best parameters for 2 subset are: 4 0.050100000000000006  with error:  0.780237177066464
Best parameters for 3 subset are: 4 0.0001  with error:  0.7895958031286999


###### Gradient descent

In [269]:
w_list, loss_list=GradientDescentSubmission(y2,tX_22, max_iters=1000, gamma=0.05)
loss_list

[0.885598012264926, 0.9092724483603103, 0.8433898349896397, 0.934406000498198]

###### Stochastic gradient descent

In [270]:
w_list, loss_list=StochasticGradientDescentSubmission(y2, tX_22,max_iters=1000,gamma=0.01,batch_size=1)
loss_list

[0.9991412156473284,
 0.9571575913025117,
 0.9039585455435363,
 0.9921416560314384]

###### Logistic regression

In [271]:
w_list, loss_list=LogisticRegressionSubmission(y2, tX_22, max_iter=10000,threshold=1e-6,gamma=0.00001)

Best loss for subset 0=-39100.22614569591
Best loss for subset 1=-41929.26275216942
Best loss for subset 2=-25970.765912595896
Best loss for subset 3=-11703.940815078236


###### Logistic penalized regression

In [ ]:
res_gammas,res_lambdas,res_losses=PenalizedLogisticRegressionValidation(y2, tX_22, max_iters=2000,threshold=1e-6,k_fold = 4,seed=1,gammas = [0.00001],lambdas =[0.01])
res_losses

In [ ]:
w_list, loss_list=PenalizedLogisticRegressionSubmission(y2, tX_22, max_iters = 2000,threshold = 1e-6,gammas = res_gammas,lambdas = res_lambdas)
loss_list